### ISSUE TITLE
CI Code owner approval not working in PR with multiple codeowners.

### ISSUE THREAD

**Issue by janiversen** [home-assistant/service-hub#251] opened 2024-05-26 08:46 UTC
Our CI now checks correctly for code owner approval for integrations with platinum status, and this works well.

However if a PR affect multiple platinum integrations the first approval “shadows” missing approval from the rest.

see https://github.com/home-assistant/core/pull/118129

@thecode approved the PR while I among others asked for changes….CI gave incorrectly green light to code owner approval.

also opened in core repo as https://github.com/home-assistant/core/issues/118160

**Comment by bdraco** [comment] 2024-05-26 09:03
I think this is working as intended, as otherwise we would need codeowner approval from every codeowner for integrations set to platinum when we are making changes to internals that affect a large number of integrations.  

For example when we fixed the race in awaiting config entry platforms, we needed to change how platforms were forwarded. It wouldn't be practical to require every codeowner with a platinum integration to review and approve that change.

**Comment by janiversen** [comment] 2024-05-26 09:19
That is a good valid argument, but the documentation states it differently.

Cases you mention can always be merged without a green CI, so that is not a blocker.

in the PR I highlight I am pretty sure the changes to modbus will again generate flaky tests, so ignoring my request for changes and merge it based on the approval would be wrong or not ?

**Comment by joostlek** [comment] 2024-05-26 10:18
I mean, when anyone creates a comment on a PR, either codeowner, core member, contributor or just someone passing by, we should still check their comments and see if it makes sense.

So someone saying, hey, we should investigate if this doesn't introduce this previous scenario, should lead to checking if this is the case.

And even if in the case it was merged without the comment (I mean, we can't expect every platinum code owner to respond in a few days), and we find out certain tests are failing, we investigate. I think that's also part of the shared responsibility in core.

**Comment by janiversen** [comment] 2024-05-26 10:36
Good argument, but that is valid for a PR against a single integration as well.

I guess my confusion is simple, the quality scale states "Integrations that reach platinum level will require approval by the code owner for each PR." but you are both arguing why that is not the case.

If it is ok to make a PR which addresses several integrations and not get code owner approval, then it makes little sense to enforce it for simple PRs, and the documentation at least should be changed.

I personally think it's a mistake to change it. I think most maintainers of platinum integrations have proven that they take their responsibility serious, and we should acknowledge that.

We have lately had several PR with multiple integrations that make changes to e,g, conform to PEP rules, several of these was luckily closed without merge. Making such changes without a code owner approval, makes it's difficult to stay on top of the code and at least one of them caused problems in the modbus integration.

It is difficult to have it both ways (apart from single cases where a rapid change is needed for stability) we either have code owner approval or we do not.

**Comment by frenck** [comment] 2024-05-26 10:47
As stated above, this is by design, reference:

https://github.com/home-assistant/service-hub/blob/6197ec1efe40a7f0c632c102278fef6a586afe4b/services/bots/src/github-webhook/handlers/platinum_review.ts#L39-L42

Besides integrations, the Home Assistant project maintains a core framework with an ecosystem around it. We maintain and upgrade that ecosystem, and as a result, we will adjust multiple integrations to match these changes as well.

These refactorings to integrations to match this framework will be performed at a higher level and will always override any code owner decision.

Don't get me wrong, we value code owners' opinions on the integration level, but we have to make calls and decisions that will override them on the higher level of our whole framework.

The refactoring referenced in this issue is a good example. In this case, it affects improvements to our testing to allow us to enable more linting and thus ensure better quality across the project as a whole.

../Frenck

**Comment by joostlek** [comment] 2024-05-26 10:48
But don't get me wrong, I do agree with the general role of codeowners.

But I also think the role of code owner isn't to review to prevent bugs. Since the PR itself shouldn't contain bugs in the first place. (I mean it's a nice catch if they do, but that shouldn't be the main reason).

But I'm also thinking, what if such codeowner takes a hiatus of a month because they're going to backpack in Thailand? That would mean we can't improve some things like for example the recent FlowResult -> ConfigFlowResult type change. 

So, no, we should not completely remove the rule, but yes, I do think we should not pour it into concrete which ties the project down because we need 30 people to approve a change.

**Closed by frenck** 2024-05-26 10:47 UTC

**Comment by joostlek** [comment] 2024-05-26 10:52
Let me scope down the bug review in PR, I mean, code quality PRs like the PEP, typing, etc
